name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Check formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic
      
    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal
      
    - name: Run static analysis
      run: dotnet build --no-restore --configuration Release --verbosity normal /p:TreatWarningsAsErrors=true

  unit-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: hellocity_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Run unit tests
      run: |
        dotnet test HelloCity.Tests/HelloCity.Tests.csproj \
          --no-build \
          --configuration Release \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=hellocity_test;Username=postgres;Password=postgres"
        ApiConfigs__DBConnection: "Host=localhost;Database=hellocity_test;Username=postgres;Password=postgres"
        
    - name: Generate coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator \
          -reports:"coverage/**/coverage.cobertura.xml" \
          -targetdir:"coveragereport" \
          -reporttypes:Html
          
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport/
        
    - name: Comment coverage on PR
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        message: |
          ## 📊 Test Coverage Report
          
          Coverage report has been generated and uploaded as an artifact.
          
          **Test Results Summary:**
          - ✅ Unit tests completed
          - 📈 Coverage report available in artifacts
          
          Please review the coverage report to ensure adequate test coverage for your changes.

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: hellocity_integration_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Setup test database
      run: |
        dotnet ef database update --project HelloCity.Api/HelloCity.Api.csproj
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=hellocity_integration_test;Username=postgres;Password=postgres"
        ApiConfigs__DBConnection: "Host=localhost;Database=hellocity_integration_test;Username=postgres;Password=postgres"
        
    - name: Run API tests
      run: |
        # Start the API in background
        dotnet run --project HelloCity.Api/HelloCity.Api.csproj &
        API_PID=$!
        
        # Wait for API to start
        sleep 10
        
        # Test API endpoints
        curl -f http://localhost:5000/api/TestUser || exit 1
        
        # Stop the API
        kill $API_PID
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=hellocity_integration_test;Username=postgres;Password=postgres"
        ApiConfigs__DBConnection: "Host=localhost;Database=hellocity_integration_test;Username=postgres;Password=postgres"
        ASPNETCORE_ENVIRONMENT: Development